kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-react
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      containers:
      - name: frontend-react
        image: 0yhr0/front-end:1.0.5
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-react
  namespace: dev
spec:
  selector:
    app: frontend-react
  type: NodePort
  sessionAffinity: ClientIP
  ports: # 端口信息
    - protocol: TCP
      port: 3000  # service端口
      targetPort: 3000 # pod端口
      nodePort: 31005 # 主机端口